# Generated by Django 4.2.19 on 2025-04-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clauseembedding',
            table='clause_embedding',
        ),
    ]
