# Generated by Django 4.2.19 on 2025-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowAI', '0002_alter_clauseembedding_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='clauseembedding',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
